apiVersion: batch/v1
kind: Job
metadata:
  name: tester-curl
  namespace: default
  labels:
    app: testclient
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: testclient
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl:7.85.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                echo "==== $(date) ====";
                curl -sv --connect-timeout 3 "http://vpce-09fd909182fb354fc-esniax7u.vpce-svc-09aa14c33a0f9d42f.us-west-2.vpce.amazonaws.com" || true;
                echo "";
                sleep 1;
              done
