apiVersion: v1
kind: Pod
metadata:
  name: tester
  namespace: default
  labels:
    app: testclient
spec:
  containers:
    - name: curl
      image: curlimages/curl:7.85.0
      command: ["sleep", "3600"]
